export const Constants = {
  prod: false,
  stills_path: 'assets/stills',
  stills_thumbnails_path: 'assets/stills/thumbnails',
  videos_path: 'assets/videos/videos',
  videos_images_path: 'assets/videos/images',
  music_path: 'assets/music',
  music_images_path: 'assets/music/images',
  image_extension: '.jpg',
  video_extension: '.mp4',
  music_extension: '.mp3',
  temp_upload_path: 'assets/temp',
  video_mimetype: 'video/mp4',
  image_mimetype: 'image/jpeg',
  music_mimetype: 'audio/mpeg',
  port: 3000,
};
